### ISSUE TITLE
App got stuck in splash screen ( Run Distribution )

### ISSUE THREAD

**Issue by sachin052** [05nelsonm/kmp-tor-binary#15]
The app is working fine if we run the app directly with help of IDE. But whenever I tried run using Run Distribution it got stuck at splash screen. below is the link of stack trace.
https://pastebin.com/eF8maUef

`23:49:09: Executing task 'runDistributable'...
 
Executing tasks: [runDistributable] in project C:\Users\Sachin\Documents\sphinx-kotlin-ui\desktop
 
 
> Configure project :common
Kotlin Multiplatform Projects are an Alpha feature. See: https://kotlinlang.org/docs/reference/evolution/components-stability.html. To hide this message, add 'kotlin.mpp.stability.nowarn=true' to the Gradle properties.
 
 
> Task :downloadWix SKIPPED
> Task :unzipWix UP-TO-DATE
> Task :sphinx-kotlin-core:generateCommonMainSphinxDatabaseInterface UP-TO-DATE
> Task :sphinx-kotlin-core:generateCommonMainSphinxSettingsDatabaseInterface UP-TO-DATE
> Task :sphinx-kotlin-core:compileKotlinJvm UP-TO-DATE
> Task :sphinx-kotlin-core:compileJava NO-SOURCE
> Task :sphinx-kotlin-core:jvmProcessResources UP-TO-DATE
> Task :sphinx-kotlin-core:jvmMainClasses UP-TO-DATE
> Task :sphinx-kotlin-core:jvmJar UP-TO-DATE
> Task :common:compileKotlinDesktop UP-TO-DATE
> Task :common:desktopProcessResources UP-TO-DATE
> Task :common:desktopMainClasses UP-TO-DATE
> Task :common:desktopJar UP-TO-DATE
> Task :desktop:checkRuntime UP-TO-DATE
> Task :desktop:createRuntimeImage UP-TO-DATE
> Task :desktop:compileKotlinJvm UP-TO-DATE
> Task :desktop:compileJava NO-SOURCE
> Task :desktop:jvmProcessResources NO-SOURCE
> Task :desktop:jvmMainClasses UP-TO-DATE
> Task :desktop:jvmJar UP-TO-DATE
> Task :desktop:prepareAppResources NO-SOURCE
> Task :desktop:createDistributable UP-TO-DATE
 
> Task :desktop:runDistributable
createTorManager: Setting up KmpTor for os: mingw, arch: x64 null
NetworkClientImpl: Listener SocketIOManagerImpl registered null
NetworkClientImpl: Listener NetworkRelayCallImpl registered null
java.lang.ClassNotFoundException: java.lang.management.ManagementFactory
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at io.matthewnelson.kmp.tor.internal.ProcessId$Companion.get(ProcessId.kt:22)
	at io.matthewnelson.kmp.tor.TorConfigProviderJvm.getProcessId(TorConfigProviderJvm.kt:56)
	at io.matthewnelson.kmp.tor.manager.TorConfigProvider$retrieve$builder$1.invoke(TorConfigProvider.kt:173)
	at io.matthewnelson.kmp.tor.manager.TorConfigProvider$retrieve$builder$1.invoke(TorConfigProvider.kt:136)
	at io.matthewnelson.kmp.tor.controller.common.config.TorConfig$Builder$Companion.invoke(TorConfig.kt:293)
	at io.matthewnelson.kmp.tor.manager.TorConfigProvider.retrieve$kmp_tor_manager(TorConfigProvider.kt:136)
	at io.matthewnelson.kmp.tor.manager.KmpTorLoader$load$validated$1.invokeSuspend(KmpTorLoader.kt:171)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)`

**Comment by 05nelsonm** [comment]
This is the `kmp-tor-binary` repository which provides **only** the Tor binaries. Please post issue in the `kmp-tor` repository [HERE](https://github.com/05nelsonm/kmp-tor)
